version: "3.8"

services:
  app:
    build: ./api
    image: cloudk-api:latest    # referência
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    depends_on:
      - database

  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
